
---
apiVersion: v1
kind: Service
metadata:
  name: shruthis-test-service
  labels:
    username: shruthis
    env: test
spec:
  type: ClusterIP
  selector:
    app: shruthis-test-redis
  ports:
  - name: shruthis-test-redis
    port: 6379
    targetPort: 6379
