apiVersion: apps/v1
kind: Deployment
metadata:
  name: shruthis-test-flask-deployment
  labels:
    app: shruthis-test-flask
    username: shruthis
    env: test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: shruthis-test-flask
  template:
    metadata:
      labels:
        app: shruthis-test-flask
        username: shruthis
        env: test
    spec:
      containers:
        - name: flask-test
          imagePullPolicy: Always
          image: shruthis/flask-animals
          env:
          - name: FLASK_APP
            value: "app.py"
          ports:
          - name: http
            containerPort: 5000
