apiVersion: v1
kind: Service
metadata:
  name: shruthis-hw7-redis-service
  labels:
    username: shruthis
    env: test
spec:
  type: ClusterIP
  selector:
    app: shruthis-hw7-redis
  ports:
  - name: shruthis-redis
    port: 6379
    targetPort: 6379



