---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-shruthis-hw7
  labels:
    username: shruthis
    env: test
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: rbd
  resources:
    requests:
      storage: 1Gi




